### ISSUE TITLE
`SOM()` usage with `dim` other than 3

### ISSUE THREAD

**Issue by kevglynn** [ameybarapatre/SOM#1]
I am trying to implement self-organizing maps in python, ideally in tensorflow. Thanks for your efforts here!

When using SOM() with anything other than dim=3 doesn't seem to work. I even adjusted the inputs to be an array of shape (10, 2), but maybe I'm off here?

Any help you can offer is greatly appreciated. If you need to see code, please let me know. My hope is to eventually be able to apply SOM to an arbitrarily large feature space on a large number of observations/rows. Thanks!

**Comment by ameybarapatre** [comment]
The map dimensions go in the parameter 'm'  where 'm' is an array of dimensions of the SOM , in the test.py file it is  a 2D Map of size 20 X 30 so m = [20,30]. You can increase the number of dimensions and size of the map by passing an appropriate array.

The parameter dim is the number of features in the input, in the test.py file it is 3.

To train the Map to use the train function and pass the input array to it. Look at test.py for reference.
